import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { MessageCircle } from "lucide-react";
import { Section, Accordion } from "@/components/ui";
import { Link } from "@/i18n/navigation";
import { buildMetadata } from "@/lib/seo";
import { CONTENT_FRESHNESS_AR, CONTENT_FRESHNESS_EN, CONTENT_LAST_REVIEW_AR, CONTENT_LAST_REVIEW_EN } from "@/lib/content-meta";
import { siteConfig, whatsappLink } from "@/lib/site";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  const ar = locale === "ar";
  return buildMetadata({ locale, path: "/register-business-in-aseza", title: ar ? "تسجيل شركة في منطقة العقبة الاقتصادية الخاصة | دليل عملي" : "Register a Company in Aqaba Special Economic Zone | Practical Guide", description: ar ? "دليل عملي لتسجيل شركة أو مؤسسة في ASEZA، يشمل الأهلية، الوثائق، الخطوات، الرسوم، المدة، ومتطلبات ما بعد التسجيل." : "Practical registration guide for setting up a company in ASEZA, including eligibility, documents, steps, fees, timeline, and post-registration licensing." });
}

export default async function Page({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params; setRequestLocale(locale); const ar = locale === "ar";
  return <main>
    <Section width="wide"><h1 className="text-3xl font-bold text-primary md:text-5xl">{ar?"تسجيل شركة في منطقة العقبة الاقتصادية الخاصة":"Registering a Company in the Aqaba Special Economic Zone"}</h1><p className="mt-3 text-primary-600">{ar?"صفحة إرشادية قبل البدء مع مكتبنا القانوني الخاص. شهادة التسجيل لا تعني تلقائياً السماح بالتشغيل دون تراخيص إضافية حسب النشاط.":"This is a practical pre-engagement guide from a private law firm. A registration certificate does not always mean immediate permission to operate."}</p><p className="mt-2 text-sm text-primary-500">{ar?`آخر مراجعة: ${CONTENT_LAST_REVIEW_AR}`:`Last reviewed: ${CONTENT_LAST_REVIEW_EN}`} — {ar?CONTENT_FRESHNESS_AR:CONTENT_FRESHNESS_EN}</p></Section>
    <Section width="wide" background="muted"><h2 className="text-2xl font-bold text-primary">{ar?"من يحق له التسجيل؟":"Who can register?"}</h2><ul className="mt-3 list-disc ps-5 text-primary-600"><li>{ar?"أفراد أردنيون أو أجانب وفق النشاط المسموح.":"Jordanian or foreign individuals, depending on activity rules."}</li><li>{ar?"شركات قائمة تريد التسجيل أو فتح فرع.":"Existing companies opening a branch or registering within ASEZA."}</li><li>{ar?"مؤسسات فردية أو شركة شخص واحد أو ذات مسؤولية محدودة حسب الحالة.":"Sole establishments, one-person companies, or LLCs, case by case."}</li></ul></Section>
    <Section width="wide"><h2 className="text-2xl font-bold text-primary">{ar?"الوثائق والرسوم والخطوات":"Documents, fees, and steps"}</h2><p className="mt-2 text-primary-600">{ar?"نفرق دائماً بين الرسوم الرسمية الحكومية وأتعاب الخدمة القانونية. نزوّدك بتقديرين منفصلين قبل البدء.":"We always separate official government fees from legal service fees, with separate estimates before start."}</p><ol className="mt-4 list-decimal ps-5 text-primary-600 space-y-2"><li>{ar?"مراجعة النشاط (مسموح/مقيد/يتطلب موافقة).":"Activity review (permitted/restricted/needs approvals)."}</li><li>{ar?"اختيار الشكل القانوني الأنسب.":"Select legal form."}</li><li>{ar?"تجهيز وثائق مقدم الطلب حسب نوعه.":"Prepare applicant-specific documents."}</li><li>{ar?"تقديم الملف ودفع الرسوم الرسمية.":"File submission and official fee payment."}</li><li>{ar?"استلام شهادة التسجيل ثم خطة الترخيص بعد التسجيل.":"Receive registration certificate, then post-registration licensing plan."}</li></ol></Section>
    <Section width="wide" background="muted"><h2 className="text-2xl font-bold text-primary">{ar?"بعد التسجيل: ماذا يحدث؟":"What happens after registration?"}</h2><p className="text-primary-600 mt-2">{ar?"قد تحتاج شهادات صحة عامة/سلامة عامة/بيئة أو تصريح مباشرة عمل أو كشف موقع قبل التشغيل. هذه الموافقات تبقى بقرار الجهة المختصة.":"You may still need public health, public safety, environmental approvals, work-commencement permit, or site inspection. These remain authority decisions."}</p><div className="mt-4 flex gap-3 flex-wrap"><Link href="/licensing-after-registration" className="rounded-lg border px-4 py-2">{ar?"الترخيص بعد التسجيل":"Licensing after registration"}</Link><Link href="/documents-checklists" className="rounded-lg border px-4 py-2">{ar?"الوثائق وقوائم الفحص":"Documents & checklists"}</Link></div></Section>
    <Section width="narrow"><Accordion items={[{question:ar?"ما المدة المتوقعة؟":"Expected timeline?",answer:ar?"المدة تختلف حسب نشاطك واكتمال الوثائق وسرعة الموافقات. نعطيك نطاقاً زمنياً تقديرياً بعد المراجعة الأولية.":"Timeline depends on activity type, document readiness, and approvals. We provide an estimated range after initial review."},{question:ar?"أخطاء شائعة؟":"Common mistakes?",answer:ar?"اختيار نشاط غير مناسب، تجاهل متطلبات الترخيص، أو افتراض أن كل المزايا الضريبية تنطبق تلقائياً.":"Choosing misclassified activity, ignoring licensing, or assuming incentives apply automatically."}]} /></Section>
    <Section width="default"><div className="rounded-xl bg-primary p-6 text-white text-center"><h2 className="text-2xl font-bold">{ar?"ابدأ بمراجعة النشاط قبل التسجيل":"Start with activity review before filing"}</h2><div className="mt-4 flex flex-wrap justify-center gap-3"><a href={whatsappLink(ar?"أرغب بتسجيل شركة في العقبة." : "I need company registration in Aqaba.")} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-[#25D366] px-5 py-3 font-semibold"><MessageCircle className="size-4"/>{ar?"تواصل عبر واتساب":"Contact on WhatsApp"}</a><a href={siteConfig.officialAsezaUrl} target="_blank" rel="noopener noreferrer" className="rounded-lg border border-white/40 px-5 py-3">{ar?"الموقع الرسمي لسلطة العقبة":"Official ASEZA website"}</a></div></div></Section>
  </main>;
}
