import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { Section, Card } from "@/components/ui";
import { Breadcrumb } from "@/components/ui/Breadcrumb";
import { buildMetadata } from "@/lib/seo";

const noteAr = "هذه القائمة إرشادية وليست نهائية، وقد تختلف المتطلبات حسب النشاط والشكل القانوني والجهة المختصة.";
const noteEn = "These checklists are indicative only and not final; requirements vary by activity, legal form, and authority decision.";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; const ar = locale === "ar"; return buildMetadata({ locale, path: "/documents-checklists", title: ar ? "وثائق ونماذج تسجيل شركة في ASEZA" : "ASEZA Registration Documents and Checklists", description: ar ? "قوائم فحص إرشادية للوثائق المطلوبة لتسجيل شركة أو فرع أجنبي أو نشاط استيراد وتصدير في منطقة العقبة الاقتصادية الخاصة." : "Guided document checklists for business registration, foreign investors, import/export, licensing-after-registration, and company updates in Aqaba." }); }
export default async function Page({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; setRequestLocale(locale); const ar = locale === "ar"; const cards = ar?["قائمة وثائق تسجيل شركة جديدة","قائمة وثائق المستثمر الأجنبي","قائمة فحص الاستيراد والتصدير","نموذج مراجعة النشاط قبل التسجيل","قائمة فحص الترخيص بعد التسجيل","قائمة فحص تعديل شركة قائمة","قائمة فحص تجديد التسجيل"]:["New company registration checklist","Foreign investor document checklist","Import/export checklist","Pre-registration activity review form","Licensing-after-registration checklist","Existing company amendment checklist","Registration renewal checklist"]; return <><div className="mx-auto max-w-7xl px-6 pt-4"><Breadcrumb items={[{ label: "الرئيسية", href: "/" }, { label: "تسجيل شركة", href: "/register-business-in-aseza" }, { label: "قوائم الوثائق" }]} /></div><Section width="wide"><h1 className="text-3xl font-bold text-primary">{ar?"النماذج والوثائق وقوائم الفحص":"Documents, Forms, and Checklists"}</h1><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{cards.map((c)=><Card key={c}><h2 className="font-semibold text-primary">{c}</h2><p className="mt-2 text-sm text-primary-600">{ar?noteAr:noteEn}</p></Card>)}</div></Section></>; }
